version: '3.8'
services:
  app:
    image: bamidele0102/backend-app:v1.3  # Updated the image tag version
    build:
      context: .
      dockerfile: Dockerfile  # Points to the Dockerfile in the root directory
    container_name: backend-app
    env_file:
      - .env  # Reference the environment variables from the .env file
    ports:
      - "3000:3000"  # Map the container port directly to port 3000 on the host
    restart: unless-stopped  # Restarts the container if it crashes
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}  # Use the MongoDB Atlas URI
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network  # Connect to the app-network defined below

networks:
  app-network:
    driver: bridge  # Bridge network for internal communication
