version: '3'
services:
  app:
    image: nodecraft-backend-app:latest  # You can use a tag like 'latest' or 'production'
    build:
      context: .
      dockerfile: Dockerfile  # Points to the Dockerfile in the root directory
    container_name: nodecraft-backend-app
    env_file:
      - .env  # Reference the environment variables from the .env file
    ports:
      - "${PORT}:3000"  # Map the container port to the host port, based on the PORT variable in .env
    restart: unless-stopped  # Restarts the container if it crashes
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/usr/src/app  # Mounts your local code into the container for development
    depends_on:
      - mongo-atlas
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# MongoDB Atlas doesn't need a service here since it's managed remotely

